[package]
name = "teamspeak-management-tools"
version = "3.3.0-alpha"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1.68"
chrono = "0.4.19"
clap = { version = "4", features = ["cargo"] }
country-emoji = "^0.2"
env_logger = "0.10"
futures-util = "0.3.21"
kstool = "0.2.1"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
once_cell = "^1.10"
redis = { version = "0.23", features = ["tokio-comp"] }
serde = "1"
serde-teamspeak-querystring = "0.2.1"
serde_derive = "1"
serde_json = "1"
sqlx = { version = "^0.7", features = ["sqlite", "runtime-tokio-rustls"], optional = true }
tap = "1"
teloxide = { version = "0.12.2", default-features = false, features = ["rustls"] }
teloxide-macros = "0.7.0"
tokio = { version = "1", features = ["full"] }
toml = "^0.7"
uuid = { version = "1", features = ["v4"] }


[profile.release]
lto = true
panic = "abort"

[features]
default = []
all = ["tracker"]
tracker = ["sqlx"]
