[package]
name = "teamspeak-management-tools"
version = "3.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = "0.4.19"
clap = { version = "4.0.8", features = ["cargo"] }
country-emoji = "0.2.0"
env_logger = "0.10.0"
futures-util = "0.3.21"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
once_cell = "1.10"
redis = { version = "0.23.0", features = ["tokio-comp"] }
serde = "1.0"
serde-teamspeak-querystring = "0.2.1"
serde_derive = "1.0"
serde_json = "1.0.79"
teloxide = { version = "0.12.2", default-features = false, features = ["rustls"] }
teloxide-macros = "0.7.0"
tokio = { version = "1.24.2", features = ["full"] }
toml = "0.7.3"
kstool = "0.1.2"
tap = "1.0.1"
async-trait = "0.1.68"
sqlx = { version = "0.7.0-alpha.3", features = ["sqlite", "runtime-tokio-rustls"], optional = true }

[profile.release]
lto = true
panic = "abort"

[features]
default = []
tracker = ["sqlx"]
